Repository abodnar1/rancid-tomatillos, pull requests merged in 2022-07, with the labels that each got.

#9 Feature/component architecture
  src/App.js
  src/MovieCard.js
  src/Movies.js
  src/index.js
  src/logo.svg
  src/movieData.js
  src/reportWebVitals.js
Labels: 1 iteration, functionality

#10 Add styling for all movies display
  src/MovieCard.js
  src/index.css
Labels: UX/UI, 1 iteration

#11 add onclick movie handler
  public/index.html
  src/App.css
  src/App.js
  src/MovieCard.css
  src/MovieCard.js
  src/MovieDetail.css
  src/MovieDetail.js
  src/Movies.css
  src/Movies.js
  src/index.css
Labels: enhancement, 2 iteration

#14 Feature/api calls
  src/App.js
  src/MovieDetail.js
Labels: enhancement, 3 iteration, functionality

#18 Feature/router refactor
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/MovieCard/MovieCard.js
  src/MovieDetail/MovieDetail.js
  src/index.js
Labels: enhancement, 4 iteration, functionality

#26 Update README.md
  README.md
Labels: documentation

#30 remove console logs, adjust formatting
  src/App/App.js
  src/Footer/Footer.js
  src/Header/Header.css
  src/Header/Header.js
  src/MovieCard/MovieCard.js
  src/MovieDetail/MovieDetail.js
  src/Movies/Movies.js
  src/index.css
  src/index.js
  src/movieData.js
Labels: 5 iteration
